### ISSUE TITLE
FunctionClauseError error

### ISSUE THREAD

**Issue by hlongvu** [annkissam/rummage_ecto#80]
I got this error with rummage_ecto 2.0.0-rc.0

`Request: GET /products?page=1
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Keyword.merge/2
        (elixir) lib/keyword.ex:704: Keyword.merge([repo: nil, per_page: 10, search: Rummage.Ecto.Hook.Search, sort: Rummage.Ecto.Hook.Sort, paginate: Rummage.Ecto.Hook.Paginate], nil)
        (rummage_example) web/models/product.ex:3: RummageExample.Product.uniq_merge/2
        (rummage_example) web/models/product.ex:3: RummageExample.Product.rummage/2
        (rummage_example) web/controllers/product_controller.ex:12: RummageExample.ProductController.index/2`

**Comment by chevinbrown** [comment]
Same issue for me.

**Comment by aditya7iyengar** [comment]
Hi @hlongvu and @chevinbrown, Rummage Phoenix and Rummage Phoenix Example don't work with Rummage Ecto 2.0.0-rc.0 yet. I am working on it now.

**Comment by oladipo** [comment]
has this issue been resolved?
